[project]
name = "project-2-fedorova-m26-555"
version = "0.1.0"
description = ""
authors = [
    {name = "Федорова Анна",email = "annafedorova21@yandex.ru"}
]
requires-python = ">=3.10"
dependencies = [
    "prettytable==3.10.2",
]

[project.scripts]
database = "src.primitive_db.main:main"

[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["src*"]

[tool.ruff]
line-length = 88
target-version = "py310"
exclude = ["venv", ".venv", "dist", "__pycache__"]

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = []

[dependency-groups]
dev = [
    "ruff>=0.16.8,<0.17.0",
]
